name       : python-setuptools
version    : 35.0.2
release    : 10
source     :
    - https://github.com/pypa/setuptools/archive/v35.0.2.tar.gz : a7baa2533abe95879291e96c0f65fe6ce8e3fa0df096147065657e2d94b83ed3
license    :
    - MIT
component  : programming.python
summary    : Easily download, build, install, upgrade, and uninstall Python packages
description: |
    Setuptools allows the easy download, build, install, upgrade, and uninstallation of Python packages.
builddeps  :
    - pkgconfig(python-2.7)
    - python-appdirs
    - python-packaging
    - python-six
setup      : |
    # Do not rely on setuptools to install setuptools
    python bootstrap.py
build      : |
    # Don't want .exe files
    export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
    %python_setup
install    : |
    # Don't want .exe files
    export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
    %python_install
