name       : python-setuptools
version    : 40.5.0
release    : 14
source     :
    - https://github.com/pypa/setuptools/archive/v40.5.0.tar.gz : 59d550ae5e3dd8c1694994eaf9ffb300cfab2b0f204db918d30d3d6da710084e
license    : MIT
component  : programming.python
summary    : Easily download, build, install, upgrade, and uninstall Python packages
description: |
    Setuptools allows the easy download, build, install, upgrade, and uninstallation of Python packages.
builddeps  :
    - python-appdirs
    - python-packaging
    - python-six
rundeps    :
    - python-appdirs
    - python-six
    - python-packaging
environment: |
    # Don't want .exe files
    export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
setup      : |
    # Do not rely on setuptools to install setuptools
    python bootstrap.py
build      : |
    %python_setup
install    : |
    %python_install
