name       : python-setuptools
version    : 24.0.2
release    : 8
source     :
    - https://pypi.python.org/packages/21/d7/3e7e4b42d40469d2b770e10aee5b49538ecf2853eb5635d2d2536b286e2d/setuptools-24.0.2.tar.gz: efe010ea62504178246f6b3d98d588c2f67884403a7a0a99670dfbf8836ca973
license    :
    - PSF
    - ZPL
component  : programming.python
summary    : Easily download, build, install, upgrade, and uninstall Python packages
description: |
    Setuptools allows the easy download, build, install, upgrade, and uninstallation of Python packages.
builddeps  :
    - pkgconfig(python-2.7)
build      : |
    %python_setup
install    : |
    %python_install
