name       : python-setuptools
version    : 22.0.0
release    : 8
source     :
    - https://pypi.python.org/packages/f5/90/010892bde11d2da00548285da29a055e6b0e3b81592bb6021571b87f34a1/setuptools-22.0.0.tar.gz : 1324ed0b1b4929fe49c347909624dbf53989555a033419f3d45ceff4c0acd6f3
license    :
    - PSF
    - ZPL
component  : programming.python
summary    : Easily download, build, install, upgrade, and uninstall Python packages
description: |
    Setuptools allows the easy download, build, install, upgrade, and uninstallation of Python packages.
builddeps  :
    - pkgconfig(python-2.7)
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0